    
$(document).ready(function(){

    $(function(){
        $("#about_we").hover(function(){
          $("#about_we_f").slideDown(100);
           },function(){
           $("#about_we_f").slideUp(100);
        }); 
      /* 点击事件  */
      $("#pic1").click(function(){
        $("#pic1").attr("src","img/jishu2.png");
        $("#pic2").attr("src","img/pic2_1.png");
        $("#pic3").attr("src","img/pic3_1.png");
        $("#pic4").attr("src","img/pic4_1.png");
        $(".con1").show()
        $(".text1").show();
        $(".text2").hide();
        $(".text3").hide();
        $(".text4").hide();
        $(".con1").css({'display':'flex','justify-content':'space-between','flex-wrap':'wrap','align-content':'space-between'})
        $(".con2").hide()
        $(".con3").hide()
        $(".con4").hide()
      }); 
      $("#pic2").click(function(){
        $("#pic1").attr("src","img/jishu1.png");
        $("#pic2").attr("src","img/pic2_2.png");
        $("#pic3").attr("src","img/pic3_1.png");
        $("#pic4").attr("src","img/pic4_1.png");
        $(".text2").show();
        $(".text1").hide();
        $(".text3").hide();
        $(".text4").hide();
        $(".con2").css({'display':'flex','justify-content':'space-between','flex-wrap':'wrap','align-content':'space-between'})
        $(".con2").show()
        $(".con1").hide()
        $(".con3").hide()
        $(".con4").hide()
      }); 
      $("#pic3").click(function(){
        $("#pic1").attr("src","img/jishu1.png");
        $("#pic2").attr("src","img/pic2_1.png");
        $("#pic3").attr("src","img/pic3_2.png");
        $("#pic4").attr("src","img/pic4_1.png");
        $(".text3").show();
        $(".text1").hide();
        $(".text2").hide();
        $(".text4").hide();
        $(".con3").css({'display':'flex','justify-content':'space-between','flex-wrap':'wrap','align-content':'space-between'})
        $(".con3").show()
        $(".con2").hide()
        $(".con1").hide()
        $(".con4").hide()
      });
      $("#pic4").click(function(){
        $("#pic1").attr("src","img/jishu1.png");
        $("#pic2").attr("src","img/pic2_1.png");
        $("#pic3").attr("src","img/pic3_1.png");
        $("#pic4").attr("src","img/pic4_2.png");
        $(".text4").show();
        $(".text1").hide();
        $(".text2").hide();
        $(".text3").hide();
        $(".con4").css({'display':'flex','justify-content':'space-between','flex-wrap':'wrap','align-content':'space-between'})
        $(".con4").show()
        $(".con2").hide()
        $(".con3").hide()
        $(".con1").hide()
      })  
    });
});
